apiVersion: apps/v1
kind: Deployment
metadata:
  name: render-server-deployment
spec:
  selector:
    matchLabels:
      app: render-server
  replicas: 8
  template:
    metadata:
      labels:
        app: render-server
    spec:
      containers:
        - name: app
          image: localhost:5000/render-server
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "500Mi"
              cpu: "600m"
            limits:
              memory: "500Mi"
              cpu: "600m"
# > kubectl apply -f k8s/deployment.yaml
# > kubectl expose deployment render-server-deployment --type=LoadBalancer --port=8080 --target-port=3000
# (if not using a service, see https://minikube.sigs.k8s.io/docs/handbook/accessing/)
# > kubectl delete deployment render-server-deployment